issue #41 provide API for Rules #41
systopia/de.systopia.eventmessages pull request #42
Opened 2023-11-15 12:16 UTC by jojowork

this PR is supposed to enhance eventmessages extension with an API for Event Message Rules

2023-11-15 12:22 UTC, jensschuppe commented
Nice work so far! As discussed, this needs to make sure that the schema matches the current DB table structure, or adjusts it with an upgrade task.

2023-11-15 16:32 UTC, jojowork commented
I designed the Schema-XML: [xml/schema/CRM/Eventmessages/EventMessageRule.xml](https://github.com/systopia/de.systopia.eventmessages/pull/42/commits/eaba2aa0f8b2ffefd1512ef5ce2f9f441f3e89b5#diff-8d2ff9e43152364bcb7e05f34853c3ea4046331de9cc4689bbbce1d9d3d49cba)
to match with the SQL-Schema definition: https://github.com/systopia/de.systopia.eventmessages/blob/master/sql/civicrm_value_event_messages.sql

I think that it matches. Or do you see any deviations?

2023-11-16 09:04 UTC, jensschuppe commented
I haven't reviewed it yet, just wanted to note that for reviewers. In any case we'll want to use the auto-generated `auto_install.sql` in favor of the old SQL file and review for code references.

2023-11-21 13:51 UTC, dontub requested changes
Thanks for the PR!
Can you additionally drop [this line](https://github.com/systopia/de.systopia.eventmessages/blob/b057912f8db70be3cdeef3361cd9933a87cb5f43/CRM/Eventmessages/Upgrader.php#L29) as it's now done via `auto_install.sql`?

2023-11-21 13:51 UTC, dontub commented on CRM/Eventmessages/BAO/EventMessageRule.php
> +  } */
I'd suggest to remove the commented lines.

2023-11-21 13:51 UTC, dontub commented on eventmessages.civix.php
> +  public static function ts($text, $params = []) {
This change is not necessary. (Are you using an older version of civix?)

2023-11-21 13:51 UTC, dontub commented on eventmessages.civix.php
> +  public static function url($file = NULL) {
Not necessary. Seems that the same holds true for the other changes in this file. If you think this file should be updated, do this in a separate PR, please.

2023-11-21 13:51 UTC, dontub commented on xml/schema/CRM/Eventmessages/EventMessageRule.xml
> +    <comment>FK to Event</comment>
Should be the same as in the [current schema](https://github.com/systopia/de.systopia.eventmessages/blob/b057912f8db70be3cdeef3361cd9933a87cb5f43/sql/civicrm_value_event_messages.sql#L5C73-L5C73): `is this rule active`.

2023-11-21 13:51 UTC, dontub commented on xml/schema/CRM/Eventmessages/EventMessageRule.xml
> +    <type>int unsigned</type>
This field should be required.

2023-11-21 14:35 UTC, jojowork commented
I made the mentioned changes.

2023-11-22 13:02 UTC, jojowork commented
Achtung: Hier muss noch getestet werden, ob bereits erstellte Rules auch nach den Änderungen erhalten bleiben.

2023-11-24 08:05 UTC, dontub commented
@jojowork, you forgot to run `civix generate:entity-boilerplate` for your change in https://github.com/systopia/de.systopia.eventmessages/pull/42/commits/f9bfbcbb9dbde084e13ca8ea99ef6d317387f3ee.

2023-11-27 13:19 UTC, jojowork commented
> @jojowork, you forgot to run `civix generate:entity-boilerplate` for your change in [f9bfbcb](https://github.com/systopia/de.systopia.eventmessages/commit/f9bfbcbb9dbde084e13ca8ea99ef6d317387f3ee).

I updated the EventMessageRule.xml to match as good as possible to the old https://github.com/systopia/de.systopia.eventmessages/blob/master/sql/civicrm_value_event_messages.sql and then executed `civix generate:entity-boilerplate`

I hope everything is fine now.

2023-11-27 13:36 UTC, merged